map_type: costmap

obstacle_range: 25.0
raytrace_range: 28.0
transform_tolerance: 0.25

robot_radius: 0.2
inflation_radius: 0.1
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /rover_platform/laser/scan, marking: true, clearing: true}
