global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 2.0
   publish_frequency: 2.0
   width: 20.0
   height: 20.0
   resolution: 0.2
   static_map: false
   rolling_window: true
